### ISSUE TITLE
TypeScript errors

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/adrestia-multisig-coordination#6]
```
Argument type (instance: FastifyInstance<http.Server, http.IncomingMessage, http.ServerResponse>, options: PluginOptions, callback: (err?: (import("fastify").FastifyError | undefined)) => void) => void is not assignable to parameter type Plugin<http.Server, http.IncomingMessage, http.ServerResponse, PluginOptions, Function>
```
![image](https://user-images.githubusercontent.com/303881/119610226-3c111600-be3c-11eb-95f4-02dd48721b4b.png)

**Comment by AlanVerbner** [comment]
I'm not seeing that error on my local env ... (and actually `yarn build` works) ... that's weird ... you just opened your editor and you are getting that error? have you done `nvm use` and `yarn install --offline` ?

![image](https://user-images.githubusercontent.com/3750504/120498668-c950ef00-c395-11eb-8365-7670bcf6f67c.png)

**Comment by rhyslbw** [comment]
I also cannot reproduce, so let's put it down to a local state issue with my env.
